[package]
name = "resize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.24"
indicatif = "0.17.3"
image = "0.24.5"